#!/usr/bin/env python3
"""
Rebuild data/art.js (and assets/gallery/) from the artworks in the Obsidian vault.

    python3 tools/import-art.py [path/to/Commonplace]

Reads every note in "2 - Source Material/2.b - Visual Art". Front matter used:
    artist, tags (art/<medium or movement>), citations, cover, created
    optional, if you add them: museum, seen (YYYY-MM-DD), year, city
The "## Notes" section becomes the note shown on the site.

Covers that are web URLs are linked as they are. Covers that are vault images
([[IMG_0237.jpg]]) are copied into assets/gallery/, resized to 1200px and saved
WITHOUT EXIF, so phone photos do not publish their GPS location.
Requires Pillow.
"""
import json, os, re, sys, hashlib, datetime
from PIL import Image, ImageOps

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
VAULT = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser('~/Commonplace')
ART_DIR = os.path.join(VAULT, '2 - Source Material', '2.b - Visual Art')
OUT_IMG = os.path.join(ROOT, 'assets', 'gallery')
MEDIA = {'painting', 'etching', 'calligraphy', 'sculpture', 'glass', 'furniture', 'drawing', 'print', 'photograph', 'ceramics'}
os.makedirs(OUT_IMG, exist_ok=True)

def front_matter(text):
    m = re.match(r'---\n(.*?)\n---\n?(.*)', text, re.S)
    if not m:
        return {}, text
    d, cur = {}, None
    for line in m.group(1).split('\n'):
        if re.match(r'^[A-Za-z][\w-]*:', line):
            k, v = line.split(':', 1)
            cur = k.strip(); v = v.strip().strip('"').strip("'")
            d[cur] = v if v else []
        elif line.strip().startswith('- ') and cur is not None:
            if not isinstance(d[cur], list):
                d[cur] = [d[cur]] if d[cur] else []
            d[cur].append(line.strip()[2:].strip('"'))
    return d, m.group(2)

def find_attachment(name):
    for dp, dn, fn in os.walk(VAULT):
        dn[:] = [x for x in dn if not x.startswith('.')]
        if name in fn:
            return os.path.join(dp, name)
    return None

def local_cover(name):
    src = find_attachment(name)
    if not src:
        print('  missing attachment:', name)
        return None
    out = hashlib.sha1(name.encode()).hexdigest()[:12] + '.jpg'
    dst = os.path.join(OUT_IMG, out)
    if not os.path.exists(dst) or os.path.getmtime(dst) < os.path.getmtime(src):
        im = ImageOps.exif_transpose(Image.open(src)).convert('RGB')
        im.thumbnail((1200, 1200))
        im.save(dst, 'JPEG', quality=82, optimize=True, progressive=True)   # no exif passed: stripped
    return 'assets/gallery/' + out

def notes(body):
    body = body.split('## References')[0]
    body = re.sub(r'^\s*##\s*Notes\s*', '', body).strip()
    body = re.sub(r'\[\[([^\]|]+)\|([^\]]+)\]\]', r'\2', body)
    body = re.sub(r'\[\[([^\]]+)\]\]', r'\1', body)
    lines = [re.sub(r'^\s*-\s*', '', l).rstrip() for l in body.split('\n')]
    return '\n'.join(l for l in lines if l.strip()) or None

def display_title(t):
    return re.sub(r'\s*\((painting|etching|sculpture|drawing|print)\)\s*$', '', t)

works = []
for fn in sorted(os.listdir(ART_DIR)):
    if not fn.endswith('.md'):
        continue
    d, body = front_matter(open(os.path.join(ART_DIR, fn), encoding='utf-8').read())
    tags = [t.split('/', 1)[1] for t in (d.get('tags') or []) if isinstance(t, str) and t.startswith('art/')]
    medium = [t for t in tags if t.lower() in MEDIA]
    movement = [t.replace('-', ' ') for t in tags if t.lower() not in MEDIA]
    cover = d.get('cover') or ''
    if isinstance(cover, list):
        cover = cover[0] if cover else ''
    m = re.match(r'\[\[([^\]|]+)', cover)
    img = local_cover(m.group(1)) if m else (cover if cover.startswith('http') else None)
    cites = d.get('citations') or []
    cites = [cites] if isinstance(cites, str) else cites
    created = str(d.get('created') or '')
    works.append({
        't': display_title(fn[:-3]), 'artist': d.get('artist') or 'Unknown',
        'medium': medium[0].capitalize() if medium else None, 'movements': movement,
        'img': img, 'link': next((c for c in cites if c.startswith('http')), None),
        'logged': created[:10] or None,
        'museum': d.get('museum') or None, 'city': d.get('city') or None,
        'seen': d.get('seen') or None, 'year': d.get('year') or None,
        'note': notes(body),
    })

works.sort(key=lambda w: w['logged'] or '', reverse=True)
path = os.path.join(ROOT, 'data', 'art.js')
with open(path, 'w', encoding='utf-8', newline='\n') as f:
    f.write('/* Generated by tools/import-art.py on %s from the Obsidian vault. Re-run the script; do not edit by hand. */\n' % datetime.date.today())
    f.write('window.ART = ')
    json.dump({'items': works}, f, ensure_ascii=False, separators=(',', ':'))
    f.write(';\n')
print('wrote', path, len(works), 'works,', sum(1 for w in works if w['img'] and w['img'].startswith('assets/')), 'local images')
