#!/usr/bin/env python3
"""
Rebuild data/books.js and data/films.js from your Goodreads and Letterboxd exports.

    python3 tools/import-reading.py [goodreads_library_export.csv] [letterboxd_export_folder]

Defaults: ~/Downloads/goodreads_library_export.csv and ~/Downloads/films
Keep the raw exports OUT of this repo: the Goodreads file contains private notes.
Only public fields are written. Private notes and custom shelves other than
"favs" are dropped.

RETIRED: books and films are now logged in admin.html (Reading and Watching).
Running this would overwrite that log with an old export, so it refuses unless
you pass --overwrite as the first argument.
"""
import csv, json, os, re, sys, datetime

if not (len(sys.argv) > 1 and sys.argv[1] == '--overwrite'):
    sys.exit('Books and films are now logged in admin.html. This importer would overwrite that log.\n'
             'If you really mean it, run: python tools/import-reading.py --overwrite [goodreads.csv] [letterboxd_folder]')
sys.argv.pop(1)

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
GR = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser('~/Downloads/goodreads_library_export.csv')
LB = sys.argv[2] if len(sys.argv) > 2 else os.path.expanduser('~/Downloads/films')
TODAY = datetime.date.today().isoformat()

def rd(path):
    with open(path, encoding='utf-8-sig', newline='') as f:
        return list(csv.DictReader(f))

def iso(d):
    d = (d or '').strip().replace('/', '-')
    return d or None

def num(x):
    try:
        v = float(x)
        return v if v > 0 else None
    except (TypeError, ValueError):
        return None

def short_title(t):
    t = re.sub(r'\s*\([^)]*#[^)]*\)\s*$', '', t)               # (Series, #1)
    t = re.sub(r'\s*\((?:[^()]*(?:Library|Classics|Edition|Series|Texts|Volume)[^()]*)\)\s*$', '', t)
    t = t.split(': ')[0]
    return t.strip()

def write(name, var, obj):
    path = os.path.join(ROOT, 'data', name)
    with open(path, 'w', encoding='utf-8', newline='\n') as f:
        f.write('/* Generated by tools/import-reading.py on %s. Do not edit by hand; re-run the script. */\n' % TODAY)
        f.write('window.%s = ' % var)
        json.dump(obj, f, ensure_ascii=False, separators=(',', ':'))
        f.write(';\n')
    print('wrote', path)

# ---------------- books ----------------
SHELF = {'read': 'read', 'currently-reading': 'reading', 'to-read': 'to-read', 'did-not-finish': 'dnf'}
books = []
for r in rd(GR):
    shelf = SHELF.get(r['Exclusive Shelf'])
    if not shelf:
        continue
    isbn = (r['ISBN13'] or r['ISBN']).strip('="')
    tags = [s.strip() for s in r['Bookshelves'].split(',')]
    books.append({
        't': short_title(r['Title']), 'full': r['Title'], 'a': r['Author'],
        'isbn': isbn or None, 'r': num(r['My Rating']),
        'read': iso(r['Date Read']), 'added': iso(r['Date Added']),
        'shelf': shelf, 'fav': 'favs' in tags,
        'review': r['My Review'].strip() or None,
        'pages': int(r['Number of Pages']) if r['Number of Pages'].isdigit() else None,
        'year': r['Original Publication Year'] or r['Year Published'] or None,
    })
write('books.js', 'BOOKS', {'updated': TODAY, 'items': books})

# ---------------- films ----------------
P = lambda *p: os.path.join(LB, *p)
profile = rd(P('profile.csv'))[0]
ratings = {(r['Name'], r['Year']): num(r['Rating']) for r in rd(P('ratings.csv'))}
likes = {(r['Name'], r['Year']) for r in rd(P('likes', 'films.csv'))} if os.path.exists(P('likes', 'films.csv')) else set()
reviews = {}
if os.path.exists(P('reviews.csv')):
    for r in rd(P('reviews.csv')):
        reviews[(r['Name'], r['Year'], r['Watched Date'])] = r['Review'].strip()

films, index = [], {}
for r in rd(P('watched.csv')):
    k = (r['Name'], r['Year'])
    index[k] = len(films)
    films.append({'t': r['Name'], 'y': int(r['Year']) if r['Year'].isdigit() else None, 'uri': r['Letterboxd URI'],
                  'r': ratings.get(k), 'liked': k in likes, 'added': r['Date']})
by_uri = {f['uri']: i for i, f in enumerate(films)}

diary = []
for r in rd(P('diary.csv')):
    k = (r['Name'], r['Year'])
    if k not in index:
        continue
    diary.append({'f': index[k], 'date': r['Watched Date'] or r['Date'], 'r': num(r['Rating']),
                  'rewatch': r['Rewatch'] == 'Yes', 'review': reviews.get((r['Name'], r['Year'], r['Watched Date'])) or None})
diary.sort(key=lambda d: d['date'], reverse=True)

favs = [by_uri[u.strip()] for u in profile.get('Favorite Films', '').split(',') if u.strip() in by_uri]

def list_file(path):
    with open(path, encoding='utf-8-sig', newline='') as f:
        lines = f.read().split('\n')
    meta = list(csv.reader([lines[2]]))[0] if len(lines) > 2 else []
    # metadata row may span lines (multi-line description); parse the whole file instead
    with open(path, encoding='utf-8-sig', newline='') as f:
        rows = list(csv.reader(f))
    head = rows[2]
    desc = re.sub(r'<[^>]+>', '', head[4]).strip() if len(head) > 4 else ''
    start = next(i for i, row in enumerate(rows) if row[:2] == ['Position', 'Name'])
    items = []
    for row in rows[start + 1:]:
        if len(row) < 3 or not row[0]:
            continue
        k = (row[1], row[2])
        items.append({'pos': int(row[0]), 'f': index.get(k), 't': row[1], 'y': row[2]})
    return {'name': head[1], 'desc': desc, 'items': items}

lists = []
if os.path.isdir(P('lists')):
    for fn in sorted(os.listdir(P('lists'))):
        if fn.endswith('.csv'):
            lists.append(list_file(P('lists', fn)))

watchlist = [{'t': r['Name'], 'y': int(r['Year']) if r['Year'].isdigit() else None, 'uri': r['Letterboxd URI'], 'added': r['Date']}
             for r in rd(P('watchlist.csv'))] if os.path.exists(P('watchlist.csv')) else []
watchlist.reverse()

write('films.js', 'FILMS', {
    'updated': TODAY, 'user': profile['Username'], 'bio': profile.get('Bio', ''),
    'favorites': favs, 'items': films, 'diary': diary, 'lists': lists, 'watchlist': watchlist,
})
